version: '2.2'
services:
  elasticsearch:
    build: .
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=${CLUSTER_NAME}
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms${XMS} -Xmx${XMX}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    build: .
    container_name: elasticsearch2
    environment:
      - cluster.name=${CLUSTER_NAME}
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms${XMS} -Xmx${XMX}
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata2:/usr/share/elasticsearch/data
    ports:
      - 9400:9200
      - 9500:9300
    networks:
      - esnet
  elasticsearch3:
    build: .
    container_name: elasticsearch3
    environment:
      - cluster.name=${CLUSTER_NAME}
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms${XMS} -Xmx${XMX}
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata3:/usr/share/elasticsearch/data
    ports:
      - 9600:9200
      - 9700:9300
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
networks:
  esnet: